### ISSUE TITLE
problème de compose simultanés

### ISSUE THREAD

**Issue by mmortier** [etalab/adresse-pipeline#107]
cf log du 28 mars 2023 lors de l'export des données.
lors du lancement du build-dist.sh 
Error: Voie 07186_4etuf0 introuvable
    at /srv/pm2-apps/ban-plateforme/lib/formatters/csv-legacy.cjs:89:15
    at Array.map (<anonymous>)
    at prepareAdresses (/srv/pm2-apps/ban-plateforme/lib/formatters/csv-legacy.cjs:85:6)
    at Object.writeAdresses (/srv/pm2-apps/ban-plateforme/lib/distribute/writers/csv.cjs:43:7)
    at /srv/pm2-apps/ban-plateforme/lib/distribute/index.cjs:21:56
    at tryCatcher (/srv/pm2-apps/ban-plateforme/node_modules/bluebird/js/release/util.js:16:23)

Ce type d'erreur qui touche csv-legacy.cjs dans prepareAdresses indique une corruption des données lors du compose.
Il y a plusieurs moyen de lancer un compose d'une commune.
Ces différentes commandes ne tiennent pas compte les unes des autres et peuvent toucher les données en base en même temps provoquant une corruption des données.

Pour mémo on peut forcer le compose de la commune corrompue, vider les files d'attente du compose et relancer le build-dist.sh
**L'idéal est ici de gérer le lock sur la base dès qu'un compose est lancé.**
Empêchant ainsi de corrompre les données.

**Comment by MalcolmTreanor** [comment]
Salut,
Veuillez excuser mon français limité. Je suis Australie.

Existe-t-il un moyen pour moi de télécharger un fichier .csv à jour avec les 21 millions d'adresses postales complètes.

Le fichier présent aujourd'hui (généré le 28 mars) ne contient encore que 2,3 millions d'enregistrements



Hi,
Is there a way for me to download an uptodate .csv with the full 21million postal addreses.

The file present today (generated on 28th Mar) still only has 2.3million records in it.
